require 'spec_helper'

describe CatalogController do
  describe "paths generated by custom routes:" do
    it "should map {:controller => 'catalog', :action => 'viewer'} to /catalog/viewer" do
      route_for(:controller => 'catalog', 
                :id => 'sample_aip_1',
                :action => 'viewer').should == 
        {:path => '/catalog/sample_aip_1/viewer',
         :method => 'get'}
    end
  end

  describe "parameters generated from routes:" do
    it "should map /catalog/:id/viewer to {:controller => 'catalog', :id => :id, :action => 'viewer'}" do
      params_from(:get,
                  '/catalog/sample_aip_1/viewer').should ==
        {:controller => 'catalog',
         :id => 'sample_aip_1',
         :action => 'viewer'}
    end
  end
end
