require 'spec_helper'

describe CatalogController do
  describe "paths generated by custom routes:" do
    it "maps {:controller => 'catalog', :action => 'viewer'} to /catalog/viewer" do
      route_for(:controller => 'catalog', 
                :id => 'sample_aip_1',
                :action => 'viewer').should == 
        {:path => '/catalog/sample_aip_1/viewer',
         :method => 'get'}
    end
  end

  describe "parameters generated from routes:" do
    it "maps /catalog/:id/viewer to {:controller => 'catalog', :id => :id, :action => 'viewer'}" do
      params_from(:get,
                  '/catalog/sample_aip_1/viewer').should ==
        {:controller => 'catalog',
         :id => 'sample_aip_1',
         :action => 'viewer'}
    end
  end

  describe "viewer action" do
    doc_id = 'sample_aip_1'

    it "gets document and response" do
      get :viewer, :id => doc_id
      assigns[:document].should_not be_nil
      assigns[:response].should_not be_nil
    end
  end
end
